name: dns-validation-task

on:
  schedule:
    - cron: "0 0,12 * * *" # At 12 AM and 12 PM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2" # install the python version needed

      - name: upgrade python and install dnsvalidator
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/vortexau/dnsvalidator.git
          cd dnsvalidator
          python setup.py install 
          cd ..

      - name: run dsnvalidator
        run: dnsvalidator -tL resolvers.txt -threads 25 -timeout 15 --silent -o resolvers.txt

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated resolvers.txt list" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
