name: dns-validation-task

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0,12 * * *" # At 12 AM and 12 PM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: upgrade python and install dnsvalidator
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          if [ ! -d dnsvalidator/.git ]; then 
            git clone https://github.com/vortexau/dnsvalidator.git
              cd dnsvalidator
              python setup.py install 
              cd ..            
          fi

      - name: Cache DNSValidator repository
        uses: actions/cache@v2
        with:
          path: |
            dnsvalidator
          key: ${{ runner.os }}-dnsvalidator
          restore-keys: |
            ${{ runner.os }}-dnsvalidator

      - name: run dsnvalidator
        run: dnsvalidator -tL resolvers.txt -threads 25 -timeout 15 --silent -o resolvers.txt

      - name: commit files
        run: |
          if git submodule status --recursive | grep '^+' >/dev/null; then
                git submodule deinit -f .
                git rm -rf --cached .
          fi
          if ! git diff-index --quiet HEAD -- resolvers.txt; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add resolvers.txt
            git commit -m "updated resolvers.txt list" --allow-empty
          fi

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
